### ISSUE TITLE
editor.exe can not run successfully!

### ISSUE THREAD

**Issue by zhouxs1023** [PanosK92/Directus3D#14]
I lover this engine  very much!Thanks for your sharing your code!

OS: WINDOW7+IDE:  VS2017
I compiler this engine, but while I run  editor.exe, it is prompted that xinput1_4.dll is missing,I had downloaded xinput1_4.dll from internet,but editor show as below:
 
![360162007137110090](https://user-images.githubusercontent.com/905931/53642079-d7ba7880-3c6b-11e9-8dc6-ea8570644519.png)

**Comment by PanosK92** [comment]
Hi zhouxs1023,

I'm glad you like the engine and you're welcome!

XInput 1.4 is part of the Windows SDK which is used for Windows 8 and 10. Windows 7 appears to be using XInput 1.3. I am not "officialy" supporting Windows 7 but downloading xinput1_4.dll might still work, and even if it doesn't, it's used for Xbox controller input, which I presume you don't need.

Getting that white window though is most likely the renderer failing to initialize. I don't have a Windows 7 machine to work with but I've submitted some changes that might help you track the source of the problem. 

The engine will now log everything into **log.txt** until the renderer initializes successfully (at which point logging will be rendered to the log window in the editor). Each entry inside log.txt includes the namespace as well as the function it originated from.
![capture](https://user-images.githubusercontent.com/19988988/53700435-49203580-3dea-11e9-8881-1984673346e8.PNG)
![capture2](https://user-images.githubusercontent.com/19988988/53700470-94d2df00-3dea-11e9-94c6-3f13ac21d4be.PNG)

On your machine, you should be getting some errors which might give you an idea as to what might be going wrong. If you manage to fix the issue, feel free to do a pull request. If you only have some clues, let me know and I'll see what I can do 😉 

Thanks for letting me know about this zhouxs1023 👍

**Comment by zhouxs1023** [comment]
I have downloaded what you provided editor release,and xinput1_4.dll come from internet ,I run editor on my computer,but can not run successfully, error as below:
![error](https://user-images.githubusercontent.com/905931/53801505-5704c080-3f7a-11e9-9caa-22a21c04bbb3.png)

**Comment by zhouxs1023** [comment]
I haved changed xinput1_3.dll to xinput1_4.dll from system32 folder on my machine,but can still not run successfully , error as below:
![error-1](https://user-images.githubusercontent.com/905931/53801732-ea3df600-3f7a-11e9-8853-33389b576088.png)

**Comment by PanosK92** [comment]
Excellent,

This is the function which fails
https://github.com/PanosK92/Directus3D/blob/43d2047e7f7b3f13db26259242bd9ae6daadbf03/Engine/RHI/D3D11/D3D11_Device.cpp#L83

If you tweak the parameters being passed to it, you should be able to get a device setup which is supported by your GPU. If not, can you please let me know what is your GPU?

**Comment by ndrshn** [comment]
Hi Panos.

I'm getting same result when want to run. no log.txt created. I tried to run it with git bash console and recieved "Segmentation fault". What should I do? 

Thanks in advance.

Btw;
OS: win10
ide: vs 2017

**Comment by ndrshn** [comment]
Hi Panos,

I'm getting same result when I want to run. no log.txt created. I tried to run it with git bash console and recieved "Segmentation fault". What should I do?

Thanks in advance.

Btw;
OS: win10
ide: vs 2017

**Comment by PanosK92** [comment]
Hi ndrshn and thanks for letting me know 👍

So guys, I got my hands on my ancient potato laptop and it failed to start as well.
It's likely that this is the same issue, I'll investigate and commit a fix 😉

**Comment by JSandusky** [comment]
It's a bit of a tangent, but the swap-chain creation isn't very robust. Tearing flag isn't supported on older DX11 (integrated intel's in particular), so those older devices can't start the editor either.

If the first try fails, I try again changing the swapchain's m_flags (so resize works) to remove the tearing flag and that works fine on an IvyBridge IntelHD4000.

Performance is pitiful (15fps) once it gets up and running (probably too much *dead* post-process or w/e), but that's a different matter really.

**Comment by PanosK92** [comment]
Hello everyone 😃 

It turns out that it was a combination of issues causing the engine to fail on startup. Issues that the three of you mentioned as well as some other ones.

**[zhouxs1023]** Fixed an issue were the default swap-chain swap effect that was used (Swap_Flip_Discard) was supported only on [Windows 10](https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/ne-dxgi-dxgi_swap_effect). The engine will now check if it's running on Windows 10 and if it's not, it will fall back to Swap_Discard, which should be okay for Windows 7.

**[ndrshn]** Fixed an issue were some code paths would simply crash upon device creation failure. Errors are now successfully logged although it hopefully will hopefully never come to that as device creation has been improved as well.

**[JSandusky]** Thank you for accurate insight, it turns out that the tearing flag was part of the swap-chain creation problem and the flag selection has been tweaked to take the adapter into account.

Extra issues:
- Fixed a bug where Swap_Flip_Discard was also not supported by Intel adapters. Upon detecting an Intel adapter, the engine will now fall back to Swap_Discard.
- Fixed a bug where swapchain was not presenting with SwapChain_Allow_Tearing in case it was successfully enabled.
- Fixed a bug where device creation was using the default adapter, it will now use the adapter with the highest VRAM, which is most likely the best available dapter.
- Adapter detection has been moved to the very beggining of the device creation so that all available adapters are visible in log.txt, even if the renderer fails to initialize.

Here is the engine, running on my ancient potato laptop, using an Intel HD Graphics 3000.
![53359588_388289675055055_1043514003084541952_n](https://user-images.githubusercontent.com/19988988/53848385-fb532b00-3fab-11e9-9b13-0ad0572bca45.png)

Please let me know if the above fixes worked for you.

Also, thanks for taking the time to let me know about these issues 👍

**Comment by JSandusky** [comment]
HD4000 crashes in setting textures the second frame (built from source):

`D3D11 CORRUPTION: ID3D11DeviceContext::PSSetShaderResources: Third parameter, array index 0 corrupt or unexpectedly NULL. [ MISCELLANEOUS CORRUPTION #15: CORRUPTED_PARAMETER3]`

From `Imgui::RHI::RenderDrawData` the specific ImGui window is the one labeled *"Viewport"*.

If the debugger is attached I can just continue my way through it and things will survive, but any attempt to run without debugging it'll halt.

Trying to track it down, but just from what I can observe in a failed start it looks like the first frame is okay and is drawn into a small fraction of the actual viewport, then the second frame crashes, so I'm looking for it assuming it's a sequence issue with what ImGui has been given now being invalid.

**Comment by PanosK92** [comment]
Moved ImGui::Image() after the Renderer::SetResolution() which should hopefully work.
Thanks once again JSandusky!

**Comment by PanosK92** [comment]
Hi @zhouxs1023,

The reported issue (as well as the issues reported by ndrshn and JSandusky) have been addressed.
As one week has passed since your last feedback, I'll assume you have no more issues and close this issue.

Thanks
